name = "tiny-builder-api"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[[d1_databases]]
binding = "DB"
database_name = "tiny-builder-db"
database_id = "local-d1-id"

[[kv_namespaces]]
binding = "KV"
id = "local-kv-id"
